### ISSUE TITLE
Extending schema generation (openapi.json)

### ISSUE THREAD

**Issue by danionescu0** [pgjones/quart-schema#1]
Hello there. 

   I have a question about this package. In have some specific usecase about the generation of openapi.json and i'm trying to override "_build_openapi_schema" function in extension.py
  I am working on an app that uses nested blueprints, i want to know for every view function :
```
    for rule in app.url_map.iter_rules():
        func = app.view_functions[rule.endpoint]
```
What is the parent blueprint to extract the url_prefix from it and add the prefix to the documentation in some way.

Now i am having some trouble getting this information,  i've tried looping through the blueprints, my code looks like this:
```
for blueprint in app.iter_blueprints():
    if len(blueprint._blueprints) > 0:
        for bp in blueprint._blueprints:
            for def_fun in bp[0].deferred_functions:
                print(type(def_fun))
                print(dir(def_fun)
```
   but i'm getting the "deferred_functions", now i need to match the "func" from my fist code block, with the "def_fun" and i don't know how to do that.

I would appreciate any hint you could give me, thank you!

**Comment by pgjones** [comment]
This might be a bug, I would have expected the paths to be correct, i.e. including the prefixes, as output in the schema. Is this not the case?

**Comment by danionescu0** [comment]
The code above will print output like:
<class 'function'>
['__annotations__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
...
...
Which won't give me the actual route

My question is can i get for every function that i loop in this code:
`    for rule in app.url_map.iter_rules():
        func = app.view_functions[rule.endpoint]
        # func will be smth like <function get_profile at 0x7fc8da3f1d30>
`
he actual route ex: "/v2/profiles" ?

The view function looks like this:
`
@profile_bp.route('/v2/profiles', methods=['GET'])
@tag(["PROFILE"])
async def get_profiles():
    ...
`


for example:
`
func.get_actual_route() # which should be "/v2/profiles"
`

**Comment by pgjones** [comment]
I don't think I understood this. Closing due to time elapsed (probably fixed).
