### ISSUE TITLE
validate_* decorators break whenever views are bound methods

### ISSUE THREAD

**Issue by joeblackwaslike** [pgjones/quart-schema#11]
## Problem
Within the `validate_*` decorators's `decorator` function, the first call is to set an attribute on the view function to store some metadata.

Example:
```python
...
    def decorator(func: Callable) -> Callable:
        setattr(func, QUART_SCHEMA_REQUEST_ATTRIBUTE, (model_class, source))
...
```

This line raises an exception whenever the view function is a bound method, as bound method objects aren't standard objects, they use slots for storage.
```python
AttributeError: 'method' object has no attribute '_quart_schema_querystring_schema'
```

These calls appear:
* https://github.com/pgjones/quart-schema/blob/main/src/quart_schema/validation.py#L76
* https://github.com/pgjones/quart-schema/blob/main/src/quart_schema/validation.py#L109
* https://github.com/pgjones/quart-schema/blob/main/src/quart_schema/validation.py#L154
* https://github.com/pgjones/quart-schema/blob/main/src/quart_schema/validation.py#L210

## Solution?
I personally do not know the best solution to fixing this, but can propose a few to stimulate discussion.

### Solution 1:
wrap the setattr call in a try except block to catch the AttributeError
```python
try:
    setattr(func, QUART_SCHEMA_REQUEST_ATTRIBUTE, (model_class, source))
except AttributeError:
    pass
```

### Solution 2:
same as above but save the metadata on the `___func__` property of the bound method
```python
try:
    setattr(func, QUART_SCHEMA_REQUEST_ATTRIBUTE, (model_class, source))
except AttributeError:
    if hasattr(func, '__func__'):
        setattr(func.__func__, QUART_SCHEMA_REQUEST_ATTRIBUTE, (model_class, source))
```

**Comment by pgjones** [comment]
I'm not sure I understand what doesn't work here - are you using a `View` class? See also 6e63ea0ae2a6e160848c00cba6b8365085423f2d

**Comment by pgjones** [comment]
Please reopen with further information.
