### ISSUE TITLE
Optional not being observed

### ISSUE THREAD

**Issue by kevinchai** [pgjones/quart-schema#21]
In the quickstart example in the README, the `due` field is optional but results in a `400 bad request` if not passed

`curl -v -H "content-type: application/json" -d '{"due":"2020-12-08T11:19:35.818445","task":"Build an example"}' localhost:5000/` works
`curl -v -H "content-type: application/json" -d '{"task":"Build an example"}' localhost:5000` fails

Viewing on redoc shows the due field is required rather than optional.

<img width="365" alt="Screen Shot 2022-11-04 at 4 12 37 pm" src="https://user-images.githubusercontent.com/443521/199924803-b2fc9799-2396-43fd-9741-1bbabb70dfc7.png">

**Comment by pgjones** [comment]
Hmm, it might be clearer with Python3.10+ syntax `due: datetime | None` i.e. it must be supplied but can be supplied as `None`. To be fully optional it needs a default value i.e. `due: Optional[datetime] = None` (see querystring docs).

Actually maybe I should add a default value to the README?

**Comment by kevinchai** [comment]
Thanks for the clarification! I was working off README and Quickstart which didn't specify a default value. To save you the time, I searched through the docs and code and added default values using `Optional[...] = None` as that is that is used with other documentation and code files rather than the `due: ... | None` syntax in a pull request (#22).
