### ISSUE TITLE
Mandatory query parameter

### ISSUE THREAD

**Issue by robertdj** [pgjones/quart-schema#24]
Hi

I am currently building my first Quart app and really enjoying this framework! 

I use `validate_querystring` from `quart_schema`. In some routes I would like to have mandatory query parameters. As per [the docs](https://quart-schema.readthedocs.io/en/latest/how_to_guides/querystring_validation.html#querystring-validation) this is not supported by `validate_querystring`, so I check them inside the route function.
However, I would like to skip this double check :-) 

Would you consider making it possible to mark query parameters as mandatory?

**Comment by pgjones** [comment]
In principle query parameters must be optional - mandatory parts should be in the path. How does your use case differ?
The decorator itself is fairly simple if you want to copy and remove the required check, https://github.com/pgjones/quart-schema/blob/main/src/quart_schema/validation.py#L56.

**Comment by robertdj** [comment]
Thank you for the swift response. I think your argument is completely fair.

My situation is that well before I started coding another service had settled on using query parameters and some are mandatory. 
Also thanks for the link -- I'll look into using that approach.

**Comment by DanielHabenicht** [comment]
We also came across this. It is mostly a documentation issue*  and the spec seems to allow it: https://swagger.io/docs/specification/v3_0/describing-parameters/#query-parameters

*: We generate a client from the spec and the parameter is not marked as mandatory so it allows developers to make a mistake and provoke an error on our api
