### ISSUE TITLE
Cannot set request body type to 'multipart/form-data' in Swagger

### ISSUE THREAD

**Issue by lox-enterprises** [pgjones/quart-schema#28]
I've defined a schema and endpoint for uploading a file with some data:

```
@dataclass
class File:
    file: Optional[UploadFile] = None
    title: Optional[str] = None
    description: Optional[str] = None
    type: Optional[str] = None


@bp.post('/<int:entity_id>/files')
@validate_request(File, source=DataSource.FORM)
async def post_file(data: File, entity_id):
    """Add file for entity to database"""
```

So I use `source=DataSource.FORM` as mentioned in the docs (https://pgjones.gitlab.io/quart-schema/how_to_guides/request_validation.html) to handle it like form data instead of JSON.

Works great! And this is how it looks in Swagger:

![Screenshot_20230228_163957](https://user-images.githubusercontent.com/25686683/222379854-77e4be66-3114-412e-8647-29f85ed4c751.png)

It correctly shows all the fields and types and even includes an upload button. The only issue is, the request body type in Swagger is defined as `application/x-www-form-urlencoded` (only option in the drop-down). When I try out this request, it works when only sending plain field data, but when I add a file, it fails (`data` in the endpoint remains empty).

I can see no way to change this to `multipart/form-data` although I've seen Swagger examples showing this (though these examples don't use Quart-Schema, unfortunately).

It seems `source=DataSource.FORM` determines the request body type. Since there are only two options for source (the other one being `DataSource.JSON`) I see no way of getting Swagger to show/send `multipart/form-data`.

Is this a limitation of Quart-Schema, and if so: is there a solution for this?

**Comment by pgjones** [comment]
See #37, I need to think about how/if I support this.
