### ISSUE TITLE
File upload using FastAPI fails validation

### ISSUE THREAD

**Issue by lox-enterprises** [pgjones/quart-schema#29]
I'm using FastAPI to add a file field to the schema.

The implementation looks like this:

```
from fastapi import UploadFile
from dataclasses import dataclass
from quart_schema import validate_request


@dataclass
class File:
    file: UploadFile
    title: str


@bp.post('/files')
@validate_request(File, source=DataSource.FORM)
async def post_file(data: File):
    """Add file"""
```

This shows a neat file upload button in Swagger showing it's being picked up properly. However, when I use this endpoint, it fails validation and I get the message `missing 1 required positional argument: 'file'`.

It seems Quart-Schema expects `file` to be present in the form data, but because the binary data is moved to `request.files` it can no longer find it. Is this the correct assumption, and if so: how can this be remedied?

**Comment by pgjones** [comment]
The FastAPI models are likely to be incompatible with Quart-Schema. If you are looking to read an uploaded file you can use the following,

```python
from quart import request

@bp.post('/files')
@validate_request(File, source=DataSource.FORM)
async def post_file(data: File):
    """Add file"""
    files = await request.files
    ...
```

See also https://flask.palletsprojects.com/en/2.2.x/patterns/fileuploads/ (same API without the `await`)

**Comment by lox-enterprises** [comment]
@pgjones thanks for your reply. I've created a 'hybrid' approach, where I make the `UploadFile` optional, so it doesn't fail the check, but it does show the upload button in Swagger, and in handling the call, I pick up `request.files` (aborting when none are present).

Even so, would be nice if there was some way to have a file upload validated through Quart-Schema :slightly_smiling_face:

**Comment by pgjones** [comment]
See #37, I need to think about how/if I support this.
