### ISSUE TITLE
Serializing non-primitive types in Pydantic models fails in 0.15

### ISSUE THREAD

**Issue by nils-borrmann-y42** [pgjones/quart-schema#30]
Returning the following model object from a route handler fails on 0.15 with the error `Object of type PosixPath is not JSON serializable`:

```python
class Response(BaseModel):
    a: UUID
    b: Path
``` 

Looking through the recent changes I found the commit 32c8811 which probably caused this - with the commit message

> Rather than alter the raw values as provided/used by Quart (via the json, querystring or response values) the decorators and functions convert as required. This should make the extension easier to use - as adding custom JSONProviders with the previous setup was a pain.
> 
> This is backwards incompatible if the previous JSONProvider was used.
> 
> Note this may cause issues as the pydantic JSON encoding is no longer used by default, which could cause issues when encoding - however it should now be clear to a user how to fix this easily (no weird inheritance or mixins).

Well, it isn't clear to me how to fix this. Is this documented somewhere? (The [docs on the topic](https://quart-schema.readthedocs.io/en/latest/discussion/json_encoding.html) seem out of date as they still mention the pydantic encoder as the default)

(I'm also not sure if this really makes the extension easier to use, if something that didn't need any configuration now does need it.)

**Comment by pgjones** [comment]
Yep, you are correct. I've restored in 0fcab09bf8315f7e1ec04fe8b8a4bd4440232e4c
