### ISSUE TITLE
Allow dependency versions to pull minor changes only

### ISSUE THREAD

**Issue by mittalmehul** [pgjones/quart-schema#47]
**Case: The release of Pydantic v2 has broken the code**
Issue: All the dependencies are marked to pull the latest version regardless of changes made which lead to failure
Solution: Update the dependency notations as vX.X.* or vX.* alternatively we can specify it as >=v1.10,<v2.0
Kindly check screenshots for reference
**Impacts : All release tags**

<img width="1038" alt="Screenshot 2023-07-06 at 2 03 08 PM" src="https://github.com/pgjones/quart-schema/assets/20821607/7bfebe3b-7b6b-4b96-b0cd-386c3a381f79">

<img width="307" alt="Screenshot 2023-07-06 at 2 03 32 PM" src="https://github.com/pgjones/quart-schema/assets/20821607/a7cc1ab1-858d-4c3c-b13f-17b7c14bdc52">
en
<img width="454" alt="Screenshot 2023-07-06 at 2 12 12 PM" src="https://github.com/pgjones/quart-schema/assets/20821607/0c711dde-f134-4f8e-b736-672df0e91330">

<img width="1160" alt="Screenshot 2023-07-06 at 2 01 27 PM" src="https://github.com/pgjones/quart-schema/assets/20821607/e6f4a53b-1100-4fb2-92d0-16447d6d015b">

**Comment by pgjones** [comment]
It is best to use a lockfile e.g. via [PDM](https://github.com/pdm-project/pdm) to control this locally.
