### ISSUE TITLE
Response header validation with pydantic Base Model class

### ISSUE THREAD

**Issue by bselman1** [pgjones/quart-schema#52]
An exception is raised when using the ```validate_response``` decorator with a header class argument set to a class that inherits from a pydantic base model instead of a dataclass or dictionary.

```python
class TestModel(BaseModel):
    id: int

class TestHeaders(BaseModel):
    content_type: str = Field(default = 'text/html', const = True, alias = 'content-type')

@validate_response(TestModel, 200, TestHeaders)
def test_endpoint():
    model = TestModel(id = 1)
    headers = TestHeaders()
    return model, 200, headers
```
During request execution a ```ResponseHeadersValidationError``` exception will be raised on [line 243](https://github.com/pgjones/quart-schema/blob/eb98712a399ff993483b48b9177d88bcac6fd757/src/quart_schema/validation.py#L243C36-L243C36) of ```validation.py```.

The issue seems to be that the line is incorrectly checking the type of the value model against the expected header class:
```python
if isinstance(headers, dict):
    headers_model_value = _convert_headers(headers, headers_model_class)
elif type(value) == headers_model_class:
    headers_model_value = headers
elif is_dataclass(headers):
    headers_model_value = headers_model_class(**asdict(headers))
else:
    raise ResponseHeadersValidationError()
```

when it should instead be checking the type of the provided headers against the expected header class:
```python
if isinstance(headers, dict):
    headers_model_value = _convert_headers(headers, headers_model_class)
elif type(headers) == headers_model_class:
    headers_model_value = headers
elif is_dataclass(headers):
    headers_model_value = headers_model_class(**asdict(headers))
else:
    raise ResponseHeadersValidationError()
```

**Comment by pgjones** [comment]
Fixed in 070cd043622e2d67db6a9ab7297c9c09b11745c2
