### ISSUE TITLE
Bug: Swagger UI Broken

### ISSUE THREAD

**Issue by bselman1** [pgjones/quart-schema#54]
The swagger documentation page displays the following error in version 0.17:
![image](https://github.com/pgjones/quart-schema/assets/43884542/39603b21-3146-4515-bff9-1f28f48a30d2)

Looks like this is related to OpenAPI version bump in commit 4464c85 (3.03 -> 3.1).

Changing the default values for `QUART_SCHEMA_SWAGGER_JS_URL` and `QUART_SCHEMA_SWAGGER_CSS_URL` in `extension.py` to version 5 of swagger-ui seems to fix the issue.

**Comment by pgjones** [comment]
Fixed in f59345d058e753b1c8e464ef8ad317a72f1cbf4c
