### ISSUE TITLE
Missing function call for docs for deprecated routes

### ISSUE THREAD

**Issue by jspsv** [pgjones/quart-schema#75]
This is minor issue in example documentation for deprecated routes.
Ref: [Deprecating routes](https://quart-schema.readthedocs.io/en/latest/how_to_guides/documenting.html#deprecating-routes)
```python
@app.route("/")
@deprecate # missing call
async def index():
    ...
```

**Comment by pgjones** [comment]
Fixed, it should be called without the parenthesis.
